version: "3.1"

services:
  Happydb:
    image: postgres
    restart: always
    container_name: HappyDB
    volumes:
      - ./docker-volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Play_db
      POSTGRES_USER: happyKids
      POSTGRES_PASSWORD: happyKids1234
    ports:
      - "9006:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U happyKids -d postgres'"
        ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s

  server:
    build:
      context: .
    ports:
      - "9003:9003"
    container_name: HappyServer
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9003/role" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
    depends_on:
      Happydb:
        condition: service_healthy

  web-ui:
    build:
      context: ./happy-UI
    ports:
      - "9002:80"
    container_name: HappyUI
    depends_on:
      server:
        condition: service_healthy

  mqtt5:
    image: eclipse-mosquitto
    container_name: Happymqtt5
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - "9007:9007"
    networks:
      - default
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: HappyAdminer
    restart: always
    ports:
      - "9080:8080"
